### ISSUE TITLE
Greyish Background with Ambient/Environment Light

### ISSUE THREAD

**Issue by KennyChan94P** [MarlonJD/babylonjs_viewer#8]
hi, is it possible to remove the grey background caused by i believe the ambient light?

**Comment by MarlonJD** [comment]
Hello, I removed skybox for some reason. can you try like this version (without disable skybox commit):

on pubspec use this. If it's not works, I'll look into it.
```
babylonjs_viewer:
    git: 
      url: https://github.com/MarlonJD/babylonjs_viewer
      ref: 1dc86dcf8b3c6fe783a5c8037a048dfe5b7a703a
```
